### ISSUE TITLE
pretraining on R2R-CE

### ISSUE THREAD

**Issue by Bowen-sdu** [MrZihan/GridMM#10]
How to perform pretraining on R2R-CE？

**Comment by MrZihan** [comment]
GridMM is pre-trained on the R2R dataset (Matterport3D simulator) and then fine-tuned on the R2R-CE (Habitat simulator).
Perhaps there are some differences between the images in these two datasets, but the instructions in the R2R and R2R-CE are consistent.

**Comment by Bowen-sdu** [comment]
Thank you very much for your reply. It has been very helpful to me.

> GridMM is pre-trained on the R2R dataset (Matterport3D simulator) and then fine-tuned on the R2R-CE (Habitat simulator). Perhaps there are some differences between the images in these two datasets, but the instructions in the R2R and R2R-CE are consistent.
