### ISSUE TITLE
关于深度信息提取

### ISSUE THREAD

**Issue by shonnon-zxs** [MrZihan/GridMM#11]
zihan你好，想请教一个问题，我用[get_depth.py](https://github.com/MrZihan/GridMM/blob/main/preprocess/get_depth.py)提取深度信息的时候，输出np.array(state.depth, copy=False).reshape(1, WIDTH, HEIGHT)值全为0为什么，我应该怎么设置呢，非常感谢

**Comment by MrZihan** [comment]
合工大校友么？我本科也是合工大的，加个微信聊吧： 18856300260

________________________________
发件人: Eric Shannon ***@***.***>
发送时间: Friday, April 12, 2024 8:09:12 PM
收件人: MrZihan/GridMM ***@***.***>
抄送: Subscribed ***@***.***>
主题: [MrZihan/GridMM] 关于深度信息提取 (Issue #11)


zihan你好，想请教一个问题，我用get_depth.py<https://github.com/MrZihan/GridMM/blob/main/preprocess/get_depth.py>提取深度信息的时候，输出np.array(state.depth, copy=False).reshape(1, WIDTH, HEIGHT)值全为0为什么，我应该怎么设置呢，非常感谢

―
