### ISSUE TITLE
Unable to open file (unable to open file: name = '../datasets/SOON/features/filtered_butd_bboxes.hdf5'

### ISSUE THREAD

**Issue by dongxinfeng1** [MrZihan/GridMM#12]
The dataset you provide in [Baidu Netdisk] doesn't have this file. Could you provide this file？ '../datasets/SOON/features/filtered_butd_bboxes.hdf5'

**Comment by MrZihan** [comment]
Sorry for the late reply. I'm currently on a business trip and unable to access the server, so I can't upload the files you need right now. However, you should be able to find the files you need from the feature files of the [VLN-DUET](https://github.com/cshizhe/VLN-DUET) project at this [link](https://www.dropbox.com/sh/u3lhng7t2gq36td/AABAIdFnJxhhCg2ItpAhMtUBa?e=1&dl=0).
