### ISSUE TITLE
The progress of file uploads

### ISSUE THREAD

**Issue by jasscia18** [MrZihan/GridMM#2]
Hi, Zihan, I would like to inquire about the progress of file uploads, especially for the feature files and checkpoints. These documents are critical to our work and we very much look forward to being able to use them to continue our research.

Thank you for your time and assistance.

**Comment by MrZihan** [comment]
I‘m very sorry that we have not been able to reply to you in time due to other urgent matters.
The main feature files and checkpoints have been uploaded to Baidu Netdisk. In the coming week, I will double-check for any omissions and upload the documents as soon as possible.

**Comment by MrZihan** [comment]
The feature files, checkpoints and documents are uploaded. If you have any other questions, please feel free to contact me.
