### ISSUE TITLE
How can I get prevalent_aug_train_enc.jsonl, train_enc.jsonl, val_seen_enc.jsonl and val_unseen_enc.jsonl

### ISSUE THREAD

**Issue by Mercy2Green** [MrZihan/GridMM#5]
Hi Mr Zihan, Sorry to bother you.

Thank you again for your upload of pretrain_map files, these files help me run GridMM r2r_train.sh successfully. For now, I want to generate these .jsonl files myself. May I ask how did you generate or get these files?

Thank you in advance for your attention.

![Screenshot from 2024-01-09 11-19-49](https://github.com/MrZihan/GridMM/assets/32302140/5bb69b55-b875-4c39-9b8d-3000a8bc295a)

**Comment by MrZihan** [comment]
Hi!  These .jsonl files are from the project `https://github.com/cshizhe/VLN-DUET`. I didn't do any further processing.

**Comment by Mercy2Green** [comment]
Thanks!
