### ISSUE TITLE
请问什么时候会有详细的readme

### ISSUE THREAD

**Issue by zhide730** [MrZihan/GridMM#6]
您好，我最近在尝试复现这个项目，但是在配环境上遇到了一些麻烦，请问您大概什么时候会提供详细的readme和requirement.txt等文件呢？

**Comment by MrZihan** [comment]
您好！
真的是非常抱歉，因为近几个月忙于托福考试和PhD申请，加之拖延症所以耽搁了很久，属于有人在issue催才处理的状态😭。
当前所有需要的文件都已经上传网盘了。
离散环境下VLN的环境配置可参见:
https://github.com/cshizhe/VLN-DUET
连续环境下VLN的环境配置可参见:
https://github.com/YicongHong/Discrete-Continuous-VLN
近期在忙于PhD面试，但我会抽空撰写文档。
有任何问题请随时提issue。
非常感谢！

**Comment by zhide730** [comment]
嗯嗯，所以你是用两套环境分别跑的vln和vln-ce嘛，我就是不太清楚matterport3d sim要怎么和habitat共存，一个是用的docker一个是用的conda环境

**Comment by MrZihan** [comment]
理论上可以共存。
但是我跑实验的时候也是分别在两个docker容器中配环境，这样处理比较方便。
VLN和VLN-CE的实验分开在两个环境里跑。

**Comment by MrZihan** [comment]
VLN-CE的conda环境也可以放docker容器里，具体你可以先参考
https://github.com/YicongHong/Discrete-Continuous-VLN

**Comment by zhide730** [comment]
好的，非常感谢！祝你一切顺利！

**Comment by zhide730** [comment]
您好，我尝试跑了代码中的vln-ce模块，请问所需要的R2R_VLNCE_v1-2_preprocessed_BERTidx这个文件在哪儿可以下载呢？

**Comment by MrZihan** [comment]
`https://github.com/YicongHong/Discrete-Continuous-VLN/tree/main/data/datasets`, VLN-CE的所需文件基本可以在这个项目里找到的。

**Comment by MrZihan** [comment]
我也上传了这些文件到 `https://github.com/MrZihan/GridMM/tree/main/VLN_CE/data/datasets`
