### ISSUE TITLE
About 'grid_map.pt'

### ISSUE THREAD

**Issue by yueluhhxx** [MrZihan/GridMM#7]
嗨！我在尝试你们的代码时没有‘data/pretrained_models’中例如‘grid_map.pt’文件，想问下作者是否上传了呢 或者我可以在那里找到

你们的工作非常有意义，期待你的回复～祝你一切顺利！

**Comment by MrZihan** [comment]
你好！grid_map.pt是GridMM在离散环境数据集R2R上预训练的checkpoint, 作为初始化参数在连续环境数据集R2R-CE上进行微调。
我已经上传到了网盘的`data/pretrained_models` 目录下，有任何其它需要可以随时提issue。
我最近着急的事情都处理得差不多了，会开始整理代码和文档。😭

**Comment by yueluhhxx** [comment]
> pretrained_models

非常感谢！我看了新上传的百度网盘里的文件，pretrained_models/grid_map-models好像还缺少ViT-B-32.pt，我可以在哪里找到呢😎

**Comment by MrZihan** [comment]
已上传，ViT-B-32.pt是CLIP的预训练模型，也可以在CLIP的官方仓库里找到。

**Comment by yueluhhxx** [comment]
谢谢！祝你新年快乐！
